solve_question:
  description: |
    Given question:
    {question}
    
    {image_path}
    
    Based on the answer options if have: {answer_options}.
    
    Analyze and extract the provided images and text from the given content.
    - Through activities like observation, manipulation and experimentation, to deepen the understanding of plane ﬁgures by constructing them with a prospect in mind and exploring the relationship between geometrical ﬁgures, and to cultivate the ability to think and represent logically.
    - To understand the fundamental methods for constructing ﬁgures like the bisector of an angle, the perpendicular bisector of a line segment and perpendicular lines, and to make use of them in concrete situations.
    - To understand parallel translation, symmetric transformation and rotational transformation, and to explore the relationship between two geometrical ﬁgures.
    
    Analyze it, and solve the given question in step-by-step explanation.
  expected_output: |
    Export a answer in {language} where:
      - Question: [the question]
      - Explanation: [a explanation in step-by-step]
      - Answer: [the final answer]
    Format to Markdown, no '```'.
  agent: math_tutor