determine_domain:
  agent: math_teacher
  description: |
    Given a question: {question_content}.
    
    DO NOT solve the question.
    Analyze and extract the provided images and text from the given content.
      - Categorize question under its respective content domain under these domains: {algebra}, {geometry}, {statistics}
      - If the domain is unclear, categorize it as "Unknown".
  expected_output: |
    Extract the question in {language} where:
      - Domain: <the mathematics domain of the question>
      - Question: <the exactly question content without image path or any other irrelevant information>
      - Image path: <the path to the image of the question for the geometry domain only>