solve_question:
  description: |
    Given question:
    {question}
    
    To infer based on answer options if have: {answer_options}.
    
    - To understand the necessity and meaning of positive and negative numbers.
    - To understand the meaning of the four fundamental operations with positive and negative numbers.
    - To perform the four fundamental operations with positive and negative numbers.
    - To represent and process by using positive and negative numbers in concrete situations.
    Terms and Symbols: natural number, sign, absolute value.
    
    Analyze it, and solve the given question in step-by-step explanation.
  expected_output: |
    Export a answer in {language} where:
      - Question: [the question]
      - Explanation: [a explanation in step-by-step]
      - Answer: [the final answer]
    Format to Markdown, no '```'.
  agent: math_tutor